# Generated by Django 3.2.6 on 2024-02-08 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
